version: "3.6"

networks:
    jti:
        name: jtnet
        ipam:
            driver: default
            config:
                - subnet: 172.36.69.0/28

services:
    publisher:
        command: python waker.py
        container_name: kon_publisher
        hostname: host_publisher
        image: diagnosekafka:alpha
        volumes:
            - /home/raghu.neerukonda/journals/kafka-consumer-api:/journals/consumer-api
        networks:
            jti:
                ipv4_address: 172.36.69.9
        build:
            context: .
            dockerfile: dfile

    subscriber:
        command: python waker.py
        container_name: kon_subscriber
        hostname: host_subscriber
        image: diagnosekafka:alpha
        networks:
            jti:
                ipv4_address: 172.36.69.6
        depends_on:
            - publisher
        volumes:
            - /home/raghu.neerukonda/journals/kafka-consumer-api:/journals/consumer-api
