version: '3.6'

networks: 
    jta:
        name: jtapache
        ipam:
          driver: default
          config:
            - subnet: 172.36.69.0/28

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      jta:
        ipv4_address: 172.36.69.6

  kafkabroker:
    image: confluentinc/cp-kafka
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.206.207:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LEADER_IMBALANCE_PER_BROKER_PERCENTAGE: 69
    networks:
      jta:
        ipv4_address: 172.36.69.9
